### PR TITLE
Update CRF to SageResearch 3.18

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
This will allow CRF to pin to the latest frameworks. There is a previous tag for pinning to the current version in mPower 2.

### CODE REVIEW

**Comment by DanWebster** [comment]
@syoung-smallwisdom  I'm getting compile error for JsonModel missing.  This could be what Travis is seeing too:
Screen Shot 2021-02-12 at 12 35 31 PM

**Comment by syoung-smallwisdom** [comment]
No, travis is getting a different issue around photo library security.
That said, somehow your submodules aren't properly updated b/c you aren't
getting the Swift package.


*Shannon Young* | Principal Software Engineer |
Sage Bionetworks | 2901 3rd Ave, Suite 300 | Seattle, WA 98121 |
c: 206-335-8922 <206.335.8922> | e: shannon.young@sagebase.org

**Comment by syoung-smallwisdom** [comment]
@DanWebster Are you using the workspace? and did you check that the submodules were updated? I just did a fresh clone and it all loaded properly so the pins are there.

**Review by Erin-Mounts — APPROVED** [review]
Couple of nits/suggestions and a question, otherwise looks good

**Comment by DanWebster** [comment]
@syoung-smallwisdom I had the submodules pointing to a legacy version of SageResearch to keep this version buildable and in TestFlight during refactoring.  That was the source of my error.  If all looks good otherwise, I'd say merge away!

**Pull request merged**
